name: underyx
permalink: '/:categories/:year/:month/:day/:title'
timezone: UTC

exclude:
  - vendor/

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: posts
    values:
      layout: blog

markdown: redcarpet
redcarpet:
  extensions:
    - smart

analytics_id: UA-46190907-1
emoji_rodeo_id: 86ce534ae35d5129675041562f7ef58de381734c500512af38f727849d2ed434

plugins:
  - jekyll-assets

assets:
  prefix: "/assets"
  sources:
    - "_assets/css"
    - "_assets/js"
    - "_assets/img"
