version: '3.7'
services:
  app:
    build:
      context: .
      target: gatsby
    image: underyx/underyx.me/gatsby
    command: ["npx", "gatsby", "develop", "--host=0.0.0.0", "--port=8379"]
    ports:
      - 8379:8379
    volumes:
      - ./src:/app/src
